<?php

namespace IUTO\LivretBundle\Repository;

/**
 * EtudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantRepository extends \Doctrine\ORM\EntityRepository
{
//    public function findOneByName($name)
//    {
//        $qb = $this->createQueryBuilder('e');
//
//        $qb
//            ->where('e.nomEtu = :name')
//            ->setParameter('name', $name);
//
//        return $qb->getQuery()->getResult();
//    }
}
