<?php

namespace IUTO\LivretBundle\Repository;

use IUTO\LivretBundle\Entity\Etudiant;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findYearDebut()
    {
        $query = $this->_em->createQuery('SELECT YEAR(f.dateDebut) from Formation f');

        return $query->getSingleResult();
    }

    public function findYearFin()
    {
        $query = $this->_em->createQuery('SELECT YEAR(f.dateFin) from Formation f');

        return $query->getSingleResult();
    }

    public  function findAllEtudiantByFormation($id)
    {
        $query = $this->_em
            ->createQuery('SELECT e from IUTOLivretBundle:Etudiant e NATURAL JOIN Formation f WHERE f.id = :id')
            ->setParameter('id', $id);
    }

}
