<?php

namespace IUTO\LivretBundle\Repository;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findYearDebut()
    {
        $query = $this->_em->createQuery('SELECT YEAR(f.dateDebut) from Fonction f');

        return $query->getSingleResult();
    }

    public function findYearFin()
    {
        $query = $this->_em->createQuery('SELECT YEAR(f.dateFin) from Fonction f');

        return $query->getSingleResult();
    }
}
