<?php

namespace IUTO\LivretBundle\Repository;

/**
 * LivretRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivretRepository extends \Doctrine\ORM\EntityRepository
{
}
