# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
#        main:
#            class: IUTO\LivretBundle\Entity\User
#            property: idUniv
        in_memory:
            memory: ~
    access_control:
            - { path: /etudiant, roles: ROLE_student }
            - { path: /professeur, roles: ROLE_faculty }
            - { path: ^/communication, roles: ROLE_employee }
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        l3_firewall:
#            pattern: ^/
#            security: true
#            cas: false

        main:
            pattern: ^/
            anonymous: true
            provider: main
            logout:
                  invalidate_session: true
                  path: /logout
                  target: /
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
