# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        # Définition de l'user provider pour la connexion
        main:
            entity: # L'utilisateur est une entité
                # Définition du type de l'utilisateur
                # La récupération de l'utilisateur est définie dans UserRepository
               class: IUTO\LivretBundle\Entity\User

        in_memory:
            memory: ~

    # Définition des routes accessibles selon le ROLE de l'user connecté
    access_control:
            - { path: /etudiant,        roles: ROLE_student }
            - { path: /etudiant,        roles: ROLE_affiliate }
            - { path: /professeur,      roles: ROLE_faculty }
            - { path: /professeur,      roles: ROLE_affiliate }
            - { path: ^/communication,  roles: ROLE_employee }
            - { path: ^/communication,  roles: ROLE_affiliate }
            - { path: /chef,            roles: ROLE_chief }
            - { path: /chef,            roles: ROLE_affiliate }
            - { path: /administrateur,  roles: ROLE_admin }
            - { path: /administrateur,  roles: ROLE_affiliate }
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # paramètrage du firewall CAS
        l3_firewall:
            # définition des routes affectées par le firewall ( toute autres routes seront accessibles sans authentification)
            pattern: ^/(login|connexion|etudiant|professeur|communication|chef)
            # Activation de la sécurité sur les routes de pattern
            security: true
            # Activation de CAS
            cas: true

        main:
            pattern: ^/
            anonymous: true
            # Définition de l'user provider ( ce qui va nous permettre de récupérer l'utilisateur )
            # qouhaitant se connecter
            provider: main


            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
