# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
services:
    app.html2pdf:
        class: IUTO\LivretBundle\Service\HTML2PDF
    ldap:
        class: Symfony\Component\Ldap\LdapClient
        arguments:
            - ldap-univ.iut45.univ-orleans.fr   # host
            - 636         # port
            - 3           # version
            - true       # SSL
            - true        # TLS
    app.html2pdfdownload:
        class: IUTO\LivretBundle\Service\HTML2PDFdownload
