#==========================================================#
#==========================================================#
#=====================ROUTE HOME===========================#
#==========================================================#
#==========================================================#
iuto_livret_homepage:
    path:     /
    defaults: { _controller: IUTOLivretBundle:Home:index }

iuto_livret_connexion:
    path: /connexion
    defaults: { _controller: IUTOLivretBundle:Connexion:connexion}

iuto_livret_choose_module:
    path: /modules
    defaults: { _controller: IUTOLivretBundle:Home:chooseModule}

iuto_livret_logout:
    path: /logout
    defaults: { _controller: IUTOLivretBundle:Logout:logout}

#==========================================================#
#==========================================================#
#==================ROUTES MODULE ETUDIANT==================#
#==========================================================#
#==========================================================#
#==========HOME============#

iuto_livret_studenthomepage:
    path: /etudiant
    defaults: { _controller: IUTOLivretBundle:Student:studenthome }

#==========CREER PROJET====#
iuto_livret_createProject:
    path: /etudiant/create/project
    defaults: { _controller: IUTOLivretBundle:Student:createProject }

#======CONTENU PROJET======#
iuto_livret_contenuProject:
    path: /etudiant/{projet}/contenu
    defaults: { _controller: IUTOLivretBundle:Student:contenuProject }

#==========CREER PROJET====#
iuto_livret_chooseProject:
    path: /etudiant/choose/project
    defaults: { _controller: IUTOLivretBundle:Student:chooseProject }

#======COMPLETER PROJET====#
iuto_livret_completeProject:
    path: /etudiant/{projet}/complete
    defaults: { _controller: IUTOLivretBundle:Student:completeProject }

#====AJOUT MOT ET IMAGE====#
iuto_livret_add_word_image:
    path: /etudiant/{projet}/complete/words_images
    defaults: { _controller: IUTOLivretBundle:Student:addWordImage }

#=====AJOUT D'UNE IMAGE====#
iuto_livret_add_img:
    path: /etudiant/{projet}/addImg
    defaults: { _controller: IUTOLivretBundle:Student:addImage }

#=====AJOUT LOGO CLIENT====#
iuto_livret_add_logo:
    path: /etudiant/{projet}/addLogo
    defaults: { _controller: IUTOLivretBundle:Student:addLogo }

#====VALIDER MODIFICATION===#
iuto_livret_confirmCompleteProject:
    path:  /etudiant/{projet}/validate
    defaults: { _controller: IUTOLivretBundle:Student:confirmCompleteProject }

#====VOIR PROJET FINI=======#
iuto_livret_finishedProject:
    path: /etudiant/{projet}/finishedProject
    defaults: { _controller: IUTOLivretBundle:Student:viewFinishedProject }

#====SUPPRIMER UN PROJET====#
iuto_livret_deleteProject:
    path: /etudiant/delete/{projet}
    defaults: { _controller: IUTOLivretBundle:Student:deleteProjet }

iuto_livret_deleteImage:
    path: /etudiant/delete/image/{image}
    defaults: { _controller: IUTOLivretBundle:Student:deleteImage }


#==========================================================#
#==========================================================#
#==================ROUTES MODULE PROFESSEUR================#
#==========================================================#
#==========================================================#
#==========HOME============#
iuto_livret_teacherhomepage:
    path: /professeur
    defaults: { _controller: IUTOLivretBundle:Teacher:teacherhome }

#==========CORRECTION1=====#
iuto_livret_correctionProf1:
    path: /professeur/correctionProf1
    defaults: { _controller: IUTOLivretBundle:Teacher:correctionTeacher1 }

#==========CORRECTION2=====#
iuto_livret_correctionProf2:
    path: /professeur/{projet}/correctionProf2
    defaults: { _controller: IUTOLivretBundle:Teacher:correctionTeacher2 }

#==========CORRECTION3=====#
iuto_livret_correctionProf3:
    path: /professeur/{projet}/correctionProf3
    defaults: { _controller: IUTOLivretBundle:Teacher:correctionTeacher3 }

#==========CORRECTION4=====#
iuto_livret_correctionProf4:
    path: /professeur/{projet}/correctionProf4
    defaults: { _controller: IUTOLivretBundle:Teacher:correctionTeacher4 }


#=====AJOUT IMAGE ET MOT====#
iuto_livret_add_img_word_teacher:
    path: /professeur/{projet}/correction/addImgWord
    defaults: { _controller: IUTOLivretBundle:Teacher:correctionTeacherWordImage }

#====AJOUT D'UNE IMAGE======#
iuto_livret_add_img_teacher:
    path: /professeur/{projet}/correction/addImg
    defaults: { _controller: IUTOLivretBundle:Teacher:addImageCorrection }

#=====AJOUT LOGO CLIENT====#
iuto_livret_add_logo:
    path: /professeur/{projet}/addLogo
    defaults: { _controller: IUTOLivretBundle:Teacher:addLogo }


#==========PROJETS VALIDES1=====#
iuto_livret_projetsValides1:
    path: /professeur/projetsValides1
    defaults: { _controller: IUTOLivretBundle:Teacher:projetsValidesTeacher1 }

iuto_livret_teacher_deleteProjet:
    path: /professeur/teacher/delete/projet/{projet}
    defaults: { _controller: IUTOLivretBundle:Teacher:deleteProjet }

iuto_livret_teacher_deleteImage:
    path: /professeur/teacher/delete/image/{image}
    defaults: { _controller: IUTOLivretBundle:Teacher:deleteImage }

iuto_livret_teacher_choose_project:
    path: /professeur/projets/choose
    defaults: { _controller: IUTOLivretBundle:Teacher:chooseProject }

#==========================================================#
#==========================================================#
#==================ROUTES MODULE CHEF DEPARTEMENT==========#
#==========================================================#
#==========================================================#
#==========HOME============#
iuto_livret_chiefhomepage:
    path: /{id}/chef
    defaults: { _controller: IUTOLivretBundle:Chief:chiefhome }

#==========PRESENTATION====#
iuto_livret_chiefPresentation:
    path: /{id}/chef/presentation
    defaults: { _controller: IUTOLivretBundle:Chief:chiefPresentation }

#==========PRESENTATIONPDF===========#
iuto_livret_chiefEditoPrevisualiser:
    path: /chef/editoprevisualiser
    defaults: { _controller: IUTOLivretBundle:PresentationGenerator:generator }

#==========LISTE====#
iuto_livret_chiefliste:
    path: /{id}/chef/liste
    defaults: { _controller: IUTOLivretBundle:Chief:chiefliste }

#==========CORRECTION1=====#
iuto_livret_correctionChief1:
    path: /{id}/correctionChief1
    defaults: { _controller: IUTOLivretBundle:Chief:correctionChief1 }

#==========CORRECTION2=====#
iuto_livret_correctionChief2:
    path: /{id}/{projet}/correctionChief2
    defaults: { _controller: IUTOLivretBundle:Chief:correctionChief2 }

#==========CORRECTION3=====#
iuto_livret_correctionChief3:
    path: /{id}/{projet}/correctionChief3
    defaults: { _controller: IUTOLivretBundle:Chief:correctionChief3 }

#==========CORRECTION4=====#
iuto_livret_correctionChief4:
    path: /{id}/{projet}/correctionChief4
    defaults: { _controller: IUTOLivretBundle:Chief:correctionChief4 }

#==========================================================#
#==========================================================#
#================ROUTES MODULE COMMUNICATIONN==============#
#==========================================================#
#==========================================================#
#==========HOME============#
iuto_livret_communicationhomepage:
    path: /communication
    defaults: { _controller: IUTOLivretBundle:Communication:communicationhome }

#=====CREATION LIVRET======#
iuto_livret_create_livret:
    path: /communication/create/livret
    defaults: { _controller: IUTOLivretBundle:Communication:communicationCreateLivret }

#====CHOIX DES PROJETS=====#
iuto_livret_choose_livret_projects:
    path: /communication/create/livret/{livret}/chooseProjects
    defaults: { _controller: IUTOLivretBundle:Communication:communicationSelectProjects }

#=====MODIFICATION LIVRET==#
iuto_livret_modif_livret:
    path: /communication/modif/livret/{livret}
    defaults: { _controller: IUTOLivretBundle:Communication:communicationModifLivret }

#==========EDITO===========#
iuto_livret_communicationEdito:
    path: /communication/edito
    defaults: { _controller: IUTOLivretBundle:Communication:communicationedito }

#==========EDITOPDF===========#
iuto_livret_communicationEditoPrevisualiser:
    path: /communication/editoprevisualiser
    defaults: { _controller: IUTOLivretBundle:EditoGenerator:generator }

#=====GENERATION LIVRET====#
iuto_livret_communication_livret_project_choice:
    path: /communication/create/{livretId}/projects
    defaults: { _controller: IUTOLivretBundle:Communication:communicationgenerationlivret }

#=====GENERER LIVRET====#
iuto_livret_communicationLivretGenerator:
    path: /communication/generation/livretGenere
    defaults: { _controller: IUTOLivretBundle:LivretGenerator:communicationgenerationlivret }

#=====GENERATION VALIDATION CR=====#
iuto_livret_communicationvalidationCR:
    path: /communication/validation
    defaults: { _controller: IUTOLivretBundle:Communication:communicationvalidationCR }

#=====SELECTION PROJET A CORRIGER=====#
iuto_livret_communicationChoix:
    path: /communication/selection
    defaults: { _controller: IUTOLivretBundle:Communication:communicationChoix}

iuto_livret_communication_correct_projet:
    path: /communication/projet/{projet}/correction
    defaults: { _controller: IUTOLivretBundle:Communication:communicationCorrectionProjet }

iuto_livret_communication_wordImg_projet:
    path: /communication/projet/{projet}/wordImg
    defaults: { _controller: IUTOLivretBundle:Communication:communicationWordImgProjet}

iuto_livret_communication_addImg_projet:
    path: /communication/projet/{projet}/addImg
    defaults: { _controller: IUTOLivretBundle:Communication:communicationAddImage}

iuto_livret_add_logo_communication:
    path: /communication/projet/{projet}/add/logoClient
    defaults: { _controller: IUTOLivretBundle:Communication:communicationAddLogo}

iuto_livret_communicationSelectionLivret:
    path: /communication/selectionlivret
    defaults: { _controller: IUTOLivretBundle:Communication:communicationSelectionLivret}

iuto_livret_communicationChoixLivret:
    path: /communication/chooseLivret
    defaults: { _controller: IUTOLivretBundle:Communication:communicationChooseLivret}

iuto_livret_communication_deleteImage:
    path: /communication/image/{image}/delete
    defaults: { _controller: IUTOLivretBundle:Communication:communicationDeleteImage}

iuto_livret_deleteLivret:
    path: /communication/delete/livret/{livret}
    defaults: { _controller: IUTOLivretBundle:Communication:communicationDeleteLivret }



#==========================================================#
#==========================================================#
#==================ROUTES MODULES ANNEXES==================#
#==========================================================#
#==========================================================#
#=====GENERATION PDF GENERATOR=====#


iuto_livret_pdfgenerator:
    path: /generate/{id}
    defaults: { _controller: IUTOLivretBundle:PDFGenerator:generator}

#=====LOGIN VIA CAS=====#
iuto_livret_login:
    path: /login
    defaults: { _controller: IUTOLivretBundle:Login:login }


iuto_livret_download:
    path: /download/{id}
    defaults: { _controller: IUTOLivretBundle:PDFGenerator:download }

iuto_livret_download_livret:
    path: /download/livret/{id}
    defaults: { _controller: IUTOLivretBundle:PDFGenerator:downloadLivret }

iuto_livret_livretgenerator:
    path: /generate/livret/{idLivret}
    defaults: { _controller: IUTOLivretBundle:PDFGenerator:generatorMany}

#==========================================================#
#==========================================================#
#=====================ROUTES MODULES PUBLIC================#
#==========================================================#
#==========================================================#
#=====INDEX MODULE PUBLIC=====#
iuto_livret_public:
    path: /public
    defaults: {_controller: IUTOLivretBundle:Public:public }

#=====INDEX MODULE PUBLIC=====#
iuto_livret_publicProjet:
    path: /public/projets
    defaults: {_controller: IUTOLivretBundle:Public:projets}

iuto_livret_iutoProjet:
    path: /public/iuto
    defaults: {_controller: IUTOLivretBundle:Public:iuto}

#==========================================================#
#==========================================================#
#==============ROUTES MODULE ADMINISTRATEUR================#
#==========================================================#
#==========================================================#

iuto_livret_administrateur:
    path: /admin
    defaults: { _controller: IUTOLivretBundle:Administrateur:adminHome }

iuto_livret_admin_chooseUser:
    path: /admin/users
    defaults: { _controller: IUTOLivretBundle:Administrateur:adminChooseUser }

iuto_livret_admin_modifUser:
    path: /admin/manage/user/{user}
    defaults: { _controller: IUTOLivretBundle:Administrateur:modifUser }
