iuto_livret_homepage:
    path:     /
    defaults: { _controller: IUTOLivretBundle:Home:index }

#==================ROUTES MODULE ETUDIANT==================#
iuto_livret_studenthomepage:
    path: /{id}
    defaults: { _controller: IUTOLivretBundle:Student:studenthome }
#==================ROUTE MODULE PROFESSEUR===========#
iuto_livret_teacherhomepage:
    path: /{id}
    defaults: { _controller: IUTOLivretBundle:Teacher:teacherhome }
#==================ROUTE MODULE CHEF DEPARTEMENT===========#
iuto_livret_chiefhomepage:
    path: /{id}
    defaults: { _controller: IUTOLivretBundle:Chief:chiefhome }
#==================ROUTE MODULE COMMUNICATIONN=============#
iuto_livret_communicationhomepage:
    path: /{id}
    defaults: { _controller: IUTOLivretBundle:Communication:communicationhome }
#==================ROUTE MODULE CORRECTION PROF===========#
iuto_livret_correctionProf1:
    path: /correctionProf1
    defaults: { _controller: IUTOLivretBundle:Teacher:correctionTeacher1 }

