iuto_livret_homepage:
    path:     /
    defaults: { _controller: IUTOLivretBundle:Home:index }

#==================ROUTES MODULE ETUDIANT==================#
iuto_livret_studenthomepage:
    path: /{id}
    defaults: { _controller: IUTOLivretBundle:Base:base }
#==================ROUTE MODULE PROFESSEUR===========#
iuto_livret_chiefhomepage:
    path: /{id}
    defaults: { _controller: IUTOLivretBundle:Base:base }
#==================ROUTE MODULE CHEF DEPARTEMENT===========#
iuto_livret_chiefhomepage:
    path: /{id}
    defaults: { _controller: IUTOLivretBundle:Base:base }
#==================ROUTE MODULE COMMUNICATIONN=============#
iuto_livret_communicationhomepage:
    path: /{id}
    defaults: { _controller: IUTOLivretBundle:Base:base }