#==================ROUTE HOME==============================#
iuto_livret_homepage:
    path:     /
    defaults: { _controller: IUTOLivretBundle:Home:index }


#==================ROUTES MODULE ETUDIANT==================#
#==========HOME============#
iuto_livret_studenthomepage:
    path: /etudiant
    defaults: { _controller: IUTOLivretBundle:Student:studenthome }

#==========CREER PROJET====#
iuto_livret_createProject:
    path: /create/project
    defaults: { _controller: IUTOLivretBundle:Student:createProject }


#==================ROUTES MODULE PROFESSEUR================#
#==========HOME============#
iuto_livret_teacherhomepage:
    path: /professeur
    defaults: { _controller: IUTOLivretBundle:Teacher:teacherhome }

#==========CORRECTION1=====#
iuto_livret_correctionProf1:
    path: /{projet}/correctionProf1
    defaults: { _controller: IUTOLivretBundle:Teacher:correctionTeacher1 }

#==========CORRECTION2=====#
iuto_livret_correctionProf2:
    path: /{projet}/correctionProf2
    defaults: { _controller: IUTOLivretBundle:Teacher:correctionTeacher2 }

#==========CORRECTION3=====#
iuto_livret_correctionProf3:
    path: /{projet}/correctionProf3
    defaults: { _controller: IUTOLivretBundle:Teacher:correctionTeacher3 }


#==================ROUTES MODULE CHEF DEPARTEMENT==========#
#==========HOME============#
iuto_livret_chiefhomepage:
    path: /chef
    defaults: { _controller: IUTOLivretBundle:Chief:chiefhome }

#==========PRESENTATION====#
iuto_livret_chiefPresentation:
    path: /chef/presentation
    defaults: { _controller: IUTOLivretBundle:Chief:chiefPresentation }

#==========LISTE====#
iuto_livret_chiefliste:
    path: /chef/liste
    defaults: { _controller: IUTOLivretBundle:Chief:chiefliste }


#==================ROUTES MODULE COMMUNICATIONN============#
#==========HOME============#
iuto_livret_communicationhomepage:
    path: /communication
    defaults: { _controller: IUTOLivretBundle:Communication:communicationhome }

#==========EDITO===========#
iuto_livret_communicationEdito:
    path: /communication/edito
    defaults: { _controller: IUTOLivretBundle:Communication:communicationedito }

#=====GENERATION LIVRET====#
iuto_livret_communicationgenerationlivret:
    path: /communication/generation
    defaults: { _controller: IUTOLivretBundle:Communication:communicationgenerationlivret }

#=====GENERATION VALIDATION CR=====#
iuto_livret_communicationvalidationCR:
    path: /communication/validation
    defaults: { _controller: IUTOLivretBundle:Communication:communicationvalidationCR }
