#==================ROUTE HOME==============================#
iuto_livret_homepage:
    path:     /
    defaults: { _controller: IUTOLivretBundle:Home:index }

iuto_livret_connexion:
    path: /connexion
    defaults: { _controller: IUTOLivretBundle:Connexion:connexion}

iuto_livret_logout:
    path: /logout
    defaults: { _controller: IUTOLivretBundle:Logout:logout}


#==================ROUTES MODULE ETUDIANT==================#
#==========HOME============#

iuto_livret_studenthomepage:
    path: /{id}/etudiant
    defaults: { _controller: IUTOLivretBundle:Student:studenthome }

#==========CREER PROJET====#
iuto_livret_createProject:
    path: /{id}/create/project
    defaults: { _controller: IUTOLivretBundle:Student:createProject }

#==========CREER PROJET====#
iuto_livret_chooseProject:
    path: /{id}/choose/project
    defaults: { _controller: IUTOLivretBundle:Student:chooseProject }

#======COMPLETER PROJET====#
iuto_livret_completeProject:
    path: /{id}/{projet}/complete
    defaults: { _controller: IUTOLivretBundle:Student:completeProject }

#====VALIDER MODIFICATION===#
iuto_livret_confirmCompleteProject:
    path:  /{id}/{projet}/validate
    defaults: { _controller: IUTOLivretBundle:Student:confirmCompleteProject }

#====VOIR PROJET FINI=======#
iuto_livret_finishedProject:
    path: /{id}/{projet}/finishedProject
    defaults: { _controller: IUTOLivretBundle:Student:viewFinishedProject }

#==================ROUTES MODULE PROFESSEUR================#
#==========HOME============#
iuto_livret_teacherhomepage:
    path: /{id}/professeur
    defaults: { _controller: IUTOLivretBundle:Teacher:teacherhome }

#==========CORRECTION1=====#
iuto_livret_correctionProf1:
    path: /{id}/correctionProf1
    defaults: { _controller: IUTOLivretBundle:Teacher:correctionTeacher1 }

#==========CORRECTION2=====#
iuto_livret_correctionProf2:
    path: /{id}/{projet}/correctionProf2
    defaults: { _controller: IUTOLivretBundle:Teacher:correctionTeacher2 }

#==========CORRECTION3=====#
iuto_livret_correctionProf3:
    path: /{id}/{projet}/correctionProf3
    defaults: { _controller: IUTOLivretBundle:Teacher:correctionTeacher3 }

#==========CORRECTION4=====#
iuto_livret_correctionProf4:
    path: /{id}/{projet}/correctionProf4
    defaults: { _controller: IUTOLivretBundle:Teacher:correctionTeacher4 }


#==================ROUTES MODULE CHEF DEPARTEMENT==========#
#==========HOME============#
iuto_livret_chiefhomepage:
    path: /{id}/chef
    defaults: { _controller: IUTOLivretBundle:Chief:chiefhome }

#==========PRESENTATION====#
iuto_livret_chiefPresentation:
    path: /{id}/chef/presentation
    defaults: { _controller: IUTOLivretBundle:Chief:chiefPresentation }

#==========LISTE====#
iuto_livret_chiefliste:
    path: /{id}/chef/{nomDep}/liste
    defaults: { _controller: IUTOLivretBundle:Chief:chiefliste }


#==================ROUTES MODULE COMMUNICATIONN============#
#==========HOME============#
iuto_livret_communicationhomepage:
    path: /communication
    defaults: { _controller: IUTOLivretBundle:Communication:communicationhome }

#==========EDITO===========#
iuto_livret_communicationEdito:
    path: /communication/edito
    defaults: { _controller: IUTOLivretBundle:Communication:communicationedito }

#==========EDITOPDF===========#
iuto_livret_communicationEditoPrevisualiser:
    path: /communication/editoprevisualiser
    defaults: { _controller: IUTOLivretBundle:EditoGenerator:generator }

#=====GENERATION LIVRET====#
iuto_livret_communicationgenerationlivret:
    path: /communication/generation
    defaults: { _controller: IUTOLivretBundle:Communication:communicationgenerationlivret }

#=====GENERER LIVRET====#
iuto_livret_communicationLivretGenerator:
    path: /communication/generation/livretGenere
    defaults: { _controller: IUTOLivretBundle:Communication:LivretGeneratorController }

#=====GENERATION VALIDATION CR=====#
iuto_livret_communicationvalidationCR:
    path: /communication/validation
    defaults: { _controller: IUTOLivretBundle:Communication:communicationvalidationCR }
    
#=====SELECTION PROJET A CORRIGER=====#
iuto_livret_communicationChoixProjet:
    path: /communication/selection
    defaults: { _controller: IUTOLivretBundle:Communication:communicationChoix}

#=====SELECTION PROJET VALIDE=====#
iuto_livret_communicationValidationChoix:
    path: /communication/selectionvalide
    defaults: { _controller: IUTOLivretBundle:Communication:communicationChoixValide}


iuto_livret_communicationSelectionLivret:
    path: /communication/selectionlivret
    defaults: { _controller: IUTOLivretBundle:Communication:communicationSelectionLivret}

#==================ROUTES MODULES ANNEXES============#
#=====GENERATION PDF GENERATOR=====#


iuto_livret_pdfgenerator:
  path: /generate/{id}
  defaults: { _controller: IUTOLivretBundle:PDFGenerator:generator}

#=====LOGIN VIA CAS=====#
iuto_livret_login:
  path: /login
  defaults: { _controller: IUTOLivretBundle:Login:login }
