#==================ROUTE HOME==============================#
iuto_livret_homepage:
    path:     /
    defaults: { _controller: IUTOLivretBundle:Home:index }


#==================ROUTES MODULE ETUDIANT==================#
#==========HOME============#
iuto_livret_studenthomepage:
    path: /etudiant
    defaults: { _controller: IUTOLivretBundle:Student:studenthome }

#==========CREER PROJET====#
iuto_livret_createProject:
    path: /create/project
    defaults: { _controller: IUTOLivretBundle:Student:createProject }


#==================ROUTES MODULE PROFESSEUR================#
#==========HOME============#
iuto_livret_teacherhomepage:
    path: /professeur
    defaults: { _controller: IUTOLivretBundle:Teacher:teacherhome }

#==========CORRECTION1=====#
iuto_livret_correctionProf1:
    path: /{id}/correctionProf1
    defaults: { _controller: IUTOLivretBundle:Teacher:correctionTeacher1 }


#==================ROUTES MODULE CHEF DEPARTEMENT==========#
#==========HOME============#
iuto_livret_chiefhomepage:
    path: /chef
    defaults: { _controller: IUTOLivretBundle:Chief:chiefhome }

#==========PRESENTATION====#
iuto_livret_chiefPresentation:
    path: /chief/presentation
    defaults: { _controller: IUTOLivretBundle:Chief:chiefPresentation }


#==================ROUTES MODULE COMMUNICATIONN============#
#==========HOME============#
iuto_livret_communicationhomepage:
    path: /communication
    defaults: { _controller: IUTOLivretBundle:Communication:communicationhome }

#==========EDITO============#
iuto_livret_communicationEdito:
    path: /communication/edito
    defaults: { _controller: IUTOLivretBundle:Chief:communicationedito }
  