iuto_livret_homepage:
    path:     /
    defaults: { _controller: IUTOLivretBundle:Home:index }

#==================ROUTES MODULE ETUDIANT==================#
iuto_livret_studenthomepage:
    path: /{id}
    defaults: { _controller: IUTOLivretBundle:Base:base }
